version: "3"

services:
  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "MTS-Gaming"
      MAX_PLAYERS: "64"
      MAX_WOLD_SIZE: "10000"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "true"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "16"
      MODE: "survival"
      MEMORY: "4G"
      TYPE: "PAPER"
      SERVER_NAME: "survival"
      VERSION: LATEST
      MODS: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      TZ: "Australia/Melbourne"
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
    ports:
      - 25565:25565
      - 19132:19132/udp
    volumes:
      - survival:/data
      - ./config/survival/Geyser-Spigot/config.yml:/plugins/Geyser-Spigot/config.yml
    tty: true
    stdin_open: true
    restart: always
    healthcheck:
      test: mc-health
      start_period: 5m
      interval: 5s
      retries: 20

volumes:
  survival:
