version: "3"

services:
  bungeecord:
    container_name: minecraft-proxy
    image: itzg/bungeecord
    environment:
      TYPE: WATERFALL
      DEBUG: "false"
      TZ: "Australia/Melbourne"
      CFG_MOTD: "MTS-Gaming 1.18"
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - 25565:25577
    volumes:
      - ./config:/config
      - wf-server:/server
    links:
      - "survival"
    networks:
      - default
      - minecraft
  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "MTS-Gaming 1.18"
      OPS: "St0ner1995"
      ENABLE_RCON: "true"
      MAX_PLAYERS: "64"
      MAX_WOLD_SIZE: "10000"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "true"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "16"
      MODE: "survival"
      MEMORY: "8G"
      TYPE: "PAPER"
      SERVER_NAME: "survival"
      TZ: "Australia/Melbourne"
    volumes:
      - survival:/data
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft

volumes:
  wf-server:
  survival:

networks:
  minecraft: